@echo off

SET NEWLINE=^& echo.
SET PROJECT_NAME=develshelper
SET IP_NGINX=192.168.56.170
SET IP_APACHE=192.168.56.171
SET HOSTS_FILE=%WINDIR%\System32\drivers\etc\hosts

FIND /C /I "%PROJECT_NAME%.nginx" %HOSTS_FILE%
IF %ERRORLEVEL% NEQ 0 ECHO %NEWLINE%^%IP_NGINX% %PROJECT_NAME%.nginx.dev www.%PROJECT_NAME%.nginx.dev>> %HOSTS_FILE%

FIND /C /I "%PROJECT_NAME%.apache" %HOSTS_FILE%
IF %ERRORLEVEL% NEQ 0 ECHO %NEWLINE%^%IP_APACHE% %PROJECT_NAME%.apache.dev www.%PROJECT_NAME%.apache.dev>> %HOSTS_FILE%

